### ISSUE TITLE
Masterscript log error when json files don't parse correctly

### ISSUE THREAD

**Issue by mtwomey** [topcoder-platform/tc-deploy-scripts#10]
RIght now, it's silent - but doesn't work properly when this happens. This thread: 
![image](https://user-images.githubusercontent.com/7715262/108152498-c78d4500-709e-11eb-98fd-4cd7d0325dae.png)

**Comment by Gunasekar-K** [comment]
Json validation has integrated during file download

**Comment by Gunasekar-K** [comment]
released on v1.4.6
