### ISSUE TITLE
Keep all S3 variables in Prod (for any environment, dev or prod)

### ISSUE THREAD

**Issue by mtwomey** [topcoder-platform/tc-deploy-scripts#2]
This will:

1. Minimize the number of AWS accounts / S3 buckets to maintain
1. Simplify the process of making changes
1. Reduce the number of ENV variables needed in CircleCI (we only need one single set of _AWS_ACCESS_KEY_ID_ and _AWS_SECRET_ACCESS_KEY_

We coud keep dev versus prod variabes in different files on S3. For example:

`submission-processor0-DEV.json` and `submission-processor-PROD.json`

Then call them like `./master_deply_v4.2.sh -d ECS -e DEV -t $CIRCLE_SHA1 -s submission-processor-${ENV}`

Thoughts on this?

**Comment by mtwomey** [comment]
@Gunasekar-K We've been talking about this - let's track further here.

**Comment by Gunasekar-K** [comment]
PROD environment files are stored in separate S3 bucket.
